### ISSUE TITLE
Support setting arbitrary tags on assets at provision time

### ISSUE THREAD

**Issue by byxorna** [tumblr/collins#135]
Similar to https://github.com/tumblr/collins/pull/134, it would be cool if provisioning a node could automagically set any key value pair in the `attributes:` hash on a nodeclass, instead of needing to manually add support for `CONTACT` and `CONTACT_NOTES`. Should be reasonably easy to add in.

I.e. 

```
  develnode:
    operating_system: centos_5
    label: Devel Node EL5
    attributes:
      - contact: ops@company.com
      - contact_notes: http://wiki/nodeclass/develnode
      - development_mode_only: true
      - other_cool_attribute: test value
    prefix: dev
    allow_suffix: true
    requires_pool: true
    primary_role: WHATEVER
```
