### ISSUE TITLE
permissions?

### ISSUE THREAD

**Issue by windowsrefund** [tumblr/collins#345]
I am evaluating 1.3.0 have used collins-shell to add a SERVER_NODE asset

    $ collins-shell asset create --type=SERVER_NODE --tag=foo
    foo,Incomplete,SERVER_NODE,2015-07-13T16:04:26+00:00,,

Now, I'd like to delete it but know I must first set the status appropriately

    $ collins-shell asset set_status --reason='why not' --status=Decommissioned --tag=foo
    fatal  unable to run command '/home/akosmin/.gem/ruby/2.1.3/bin/collins-shell asset set_status --reason=why not --status=Decommissioned --tag=foo'
    exception  Exception talking to /api/asset/foo/status: Invalid username or password

That seems odd given my very simple permissions.conf

```
users:
  ops:
    - "akosmin"
permissions:
  feature.noRateLimit:
    - "u=ops"
  feature.canSeePasswords:
    - "u=ops"
  controllers.Admin:
    - "u=ops"
  controllers.Admin.stats:
    - "u=ops"
  controllers.AssetLogApi.getAllLogData:
    - "u=ops"
  controllers.AssetApi.createAsset:
    - "u=ops"
  controllers.AssetApi.updateAsset:
    - "u=ops"
  controllers.AssetApi.updateAssetForMaintenance:
    - "u=ops"
  controllers.AssetApi.deleteAssetAttribute:
    - "u=ops"
  controllers.AssetApi.deleteAsset:
    - "u=ops"
  controllers.AssetManagementApi.powerManagement:
    - "u=ops"
  controllers.AssetManagementApi.powerStatus:
    - "u=ops"
  controllers.AssetManagementApi.provisionAsset:
    - "u=ops"
  controllers.AssetManagementApi.getProvisioningProfiles:
    - "u=ops"
  controllers.AssetWebApi.cancelAsset:
    - "u=ops"
  controllers.AssetWebApi.deleteAsset:
    - "u=ops"
  controllers.IpAddressApi:
    - "u=ops"
```

and here's the related bits from conf/production.conf

```
conf_dir = "/usr/local/collins/current/conf"
authentication {
  permissionsFile = ${conf_dir}"/permissions.yaml"
  type = file
  file {
    userfile = ${conf_dir}"/users.conf"
  }
}
```

Am I missing something here? 

Also worth mentioning is the fact the the SERVER_NODE asset can not be deleted from the UI. There's an open issue about this which seems to have gone idle.
