### ISSUE TITLE
Provisioning profiles endpoint should expose extra data

### ISSUE THREAD

**Issue by byxorna** [tumblr/collins#410]
It is a common pattern to locate extra data with the provisioning profiles in `profiles.yaml`. For example, it is reasonable to have a profiles.yaml contain extra fields like what OS to provision, what VLAN the profile requires, what style of disk partitioning should be used, etc:

```
---
profiles:
    searchnode:
        label: "Search Server"
        prefix: "search"
        allow_suffix: true
        primary_role: "SEARCH"
        pool: "SEARCH_POOL"
        secondary_role: "MASTER"
        requires_primary_role: false
        requires_secondary_role: true
        requires_pool: false
        cobbler_profile: "centos-5.6-x86_64-db-v2"
        operating_system: "centos_5"
        vlans: ["search"]
        disks: hw_raid_10
```

When hitting the `/api/provision/profiles` endpoint, it omits all these juicy extra fields, which is very disappointing. Ideally these extra attributes could be made available to API consumers like provisioning systems to make appropriate decisions about how to do the needful. cc @Primer42 @defect @schallert @roymarantz 

The data currently returned looks like: 
```
#<Collins::Profile:0x007fdd1204d700 @options={:profile=>"devnode", :label=>"Dev Node", :prefix=>"dev", :suffix_allowed=>true, :primary_role=>"DEVELOPMENT", :requires_primary_role=>true, :pool=>"DEVELOPMENT", :requires_pool=>true, :secondary_role=>nil, :requires_secondary_role=>false}>
```

Perhaps there could be an extra field with `extras:` in it, and just dump json of all the other bits there?
